import pandas as pd
data = pd.read_csv("understat_per_game.csv")
print(data.columns.tolist())
years = data["year"].unique()
leag = data["league"].unique()
print(years)
year = input("Enter the year")
print(leag)
league = input("Enter the league:")
sc = data[data["year"] ==int(year)][data["league"] == str(league)]["scored"].sum()
print(year ,"  ",league, " =",sc)
ab = data[data["year"] ==int(year)][data["league"] == str(league)]["xG"].sum()
print(year ,"  ",league, " =",ab)
print("the difference in scoring is",sc-ab)
